import * as fs from 'fs';
import * as path from 'path';
import { generateStub } from '../src/stub-generator';
import { DiffResult } from '../src/types';

describe('generateStub', () => {
  const testProject = '__test-stub-project__';
  const migrationsDir = path.resolve(process.cwd(), 'migrations', testProject);

  afterAll(() => {
    // Cleanup the test migration directory
    if (fs.existsSync(migrationsDir)) {
      fs.rmSync(migrationsDir, { recursive: true, force: true });
    }
  });

  it('creates migration file for added collection', () => {
    const result: DiffResult = {
      collections: {
        NewModel: { type: 'added' },
      },
    };

    const filePath = generateStub(result, 'v1', 'v2', testProject);
    expect(fs.existsSync(filePath)).toBe(true);

    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain('Auto-generated by mongoose-drift');
    expect(content).toContain(testProject);
    expect(content).toContain('v1');
    expect(content).toContain('v2');
    expect(content).toContain("New collection 'NewModel'");
    expect(content).toContain('module.exports');
    expect(content).toContain('async up(db)');
    expect(content).toContain('async down(db)');
  });

  it('creates migration file for removed collection', () => {
    const result: DiffResult = {
      collections: {
        OldModel: { type: 'removed' },
      },
    };

    const filePath = generateStub(result, 'v2', 'v3', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Collection 'OldModel' removed");
    expect(content).toContain('.drop()');
  });

  it('creates migration file for added field', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'added', field: 'phone', after: { type: 'String' } },
          ],
        },
      },
    };

    const filePath = generateStub(result, 'v3', 'v4', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Add field 'phone'");
    expect(content).toContain('$set');
    expect(content).toContain('phone');
  });

  it('creates migration file for removed field', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'removed', field: 'fax', before: { type: 'String' } },
          ],
        },
      },
    };

    const filePath = generateStub(result, 'v4', 'v5', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Remove field 'fax'");
    expect(content).toContain('$unset');
  });

  it('creates migration file for modified field', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'modified', field: 'age', before: { type: 'String' }, after: { type: 'Number' } },
          ],
        },
      },
    };

    const filePath = generateStub(result, 'v5', 'v6', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Field 'age' was modified");
  });

  it('creates migration file for renamed field', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'renamed', field: 'fullName', renamedFrom: 'firstName' },
          ],
        },
      },
    };

    const filePath = generateStub(result, 'v6', 'v7', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Rename 'firstName' → 'fullName'");
    expect(content).toContain('$rename');
  });

  it('creates migration file for complex multi-collection diff', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'added', field: 'avatar', after: { type: 'String' } },
            { type: 'removed', field: 'legacy', before: { type: 'String' } },
            { type: 'modified', field: 'email', before: { type: 'String' }, after: { type: 'String', required: true } },
            { type: 'renamed', field: 'displayName', renamedFrom: 'name' },
          ],
        },
        Payment: { type: 'added' },
        OldService: { type: 'removed' },
      },
    };

    const filePath = generateStub(result, 'v7', 'v8', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');

    // All change types should be represented
    expect(content).toContain('$set');
    expect(content).toContain('$unset');
    expect(content).toContain('$rename');
    expect(content).toContain('modified');
    expect(content).toContain('New collection');
    expect(content).toContain('removed');
  });

  it('generates correct filename', () => {
    const result: DiffResult = { collections: {} };
    const filePath = generateStub(result, 'v10', 'v11', testProject);
    expect(path.basename(filePath)).toBe('v10-to-v11.js');
  });

  it('creates the migrations directory if missing', () => {
    const uniqueProject = '__test-stub-fresh__';
    const freshDir = path.resolve(process.cwd(), 'migrations', uniqueProject);

    // Ensure it doesn't exist
    if (fs.existsSync(freshDir)) {
      fs.rmSync(freshDir, { recursive: true, force: true });
    }

    const result: DiffResult = {
      collections: { X: { type: 'added' } },
    };

    const filePath = generateStub(result, 'a', 'b', uniqueProject);
    expect(fs.existsSync(filePath)).toBe(true);

    // Cleanup
    fs.rmSync(freshDir, { recursive: true, force: true });
  });
});
