import * as fs from 'fs';
import * as path from 'path';
import { generateStub } from '../src/stub-generator';
import { DiffResult } from '../src/types';

describe('generateStub', () => {
  const testProject = '__test-stub-project__';
  const migrationsDir = path.resolve(process.cwd(), 'migrations', testProject);

  afterAll(() => {
    // Cleanup the test migration directory
    if (fs.existsSync(migrationsDir)) {
      fs.rmSync(migrationsDir, { recursive: true, force: true });
    }
  });

  it('creates migration file for added collection', () => {
    const result: DiffResult = {
      collections: {
        NewModel: { type: 'added' },
      },
    };

    const filePath = generateStub(result, 'v1', 'v2', testProject);
    expect(fs.existsSync(filePath)).toBe(true);

    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain('Auto-generated by mongoose-drift');
    expect(content).toContain(testProject);
    expect(content).toContain('v1');
    expect(content).toContain('v2');
    expect(content).toContain("New collection 'NewModel'");
    expect(content).toContain('module.exports');
    expect(content).toContain('async up(db)');
    expect(content).toContain('async down(db)');
  });

  it('creates migration file for removed collection', () => {
    const result: DiffResult = {
      collections: {
        OldModel: { type: 'removed' },
      },
    };

    const filePath = generateStub(result, 'v2', 'v3', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Collection 'OldModel' removed");
    expect(content).toContain('.drop()');
  });

  it('creates migration file for added field', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'added', field: 'phone', after: { type: 'String' } },
          ],
        },
      },
    };

    const filePath = generateStub(result, 'v3', 'v4', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Add field 'phone'");
    expect(content).toContain('$set');
    expect(content).toContain('phone');
  });

  it('creates migration file for removed field', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'removed', field: 'fax', before: { type: 'String' } },
          ],
        },
      },
    };

    const filePath = generateStub(result, 'v4', 'v5', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Remove field 'fax'");
    expect(content).toContain('$unset');
  });

  it('creates migration file for modified field', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'modified', field: 'age', before: { type: 'String' }, after: { type: 'Number' } },
          ],
        },
      },
    };

    const filePath = generateStub(result, 'v5', 'v6', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Field 'age' was modified");
  });

  it('creates migration file for renamed field', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'renamed', field: 'fullName', renamedFrom: 'firstName' },
          ],
        },
      },
    };

    const filePath = generateStub(result, 'v6', 'v7', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain("Rename 'firstName' → 'fullName'");
    expect(content).toContain('$rename');
  });

  it('creates migration file for complex multi-collection diff', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          changes: [
            { type: 'added', field: 'avatar', after: { type: 'String' } },
            { type: 'removed', field: 'legacy', before: { type: 'String' } },
            { type: 'modified', field: 'email', before: { type: 'String' }, after: { type: 'String', required: true } },
            { type: 'renamed', field: 'displayName', renamedFrom: 'name' },
          ],
        },
        Payment: { type: 'added' },
        OldService: { type: 'removed' },
      },
    };

    const filePath = generateStub(result, 'v7', 'v8', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');

    // All change types should be represented
    expect(content).toContain('$set');
    expect(content).toContain('$unset');
    expect(content).toContain('$rename');
    expect(content).toContain('modified');
    expect(content).toContain('New collection');
    expect(content).toContain('removed');
  });

  it('generates correct filename', () => {
    const result: DiffResult = { collections: {} };
    const filePath = generateStub(result, 'v10', 'v11', testProject);
    expect(path.basename(filePath)).toBe('v10-to-v11.js');
  });

  it('creates the migrations directory if missing', () => {
    const uniqueProject = '__test-stub-fresh__';
    const freshDir = path.resolve(process.cwd(), 'migrations', uniqueProject);

    // Ensure it doesn't exist
    if (fs.existsSync(freshDir)) {
      fs.rmSync(freshDir, { recursive: true, force: true });
    }

    const result: DiffResult = {
      collections: { X: { type: 'added' } },
    };

    const filePath = generateStub(result, 'a', 'b', uniqueProject);
    expect(fs.existsSync(filePath)).toBe(true);

    // Cleanup
    fs.rmSync(freshDir, { recursive: true, force: true });
  });
});

// ─────────────────────────────────────────────────────
// generateStub — index changes
// ─────────────────────────────────────────────────────
describe('generateStub — index changes', () => {
  const testProject = '__test-stub-idx-project__';
  const migrationsDir = path.resolve(process.cwd(), 'migrations', testProject);

  afterAll(() => {
    if (fs.existsSync(migrationsDir)) {
      fs.rmSync(migrationsDir, { recursive: true, force: true });
    }
  });

  it('generates commented createIndex for an added index', () => {
    const result: DiffResult = {
      collections: {
        User: {
          type: 'modified',
          indexChanges: [{ type: 'added', fields: { email: 1 }, options: { unique: true } }],
        },
      },
    };
    const filePath = generateStub(result, 'idx-v1', 'idx-v2', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain('createIndex');
    expect(content).toContain('email');
    expect(content).toContain('unique');
  });

  it('generates commented dropIndex for a removed index', () => {
    const result: DiffResult = {
      collections: {
        Order: {
          type: 'modified',
          indexChanges: [{ type: 'removed', fields: { ref: -1 } }],
        },
      },
    };
    const filePath = generateStub(result, 'idx-v3', 'idx-v4', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain('dropIndex');
    expect(content).toContain('ref');
  });

  it('generates both field and index stubs in the same file', () => {
    const result: DiffResult = {
      collections: {
        Product: {
          type: 'modified',
          changes: [
            { type: 'added', field: 'sku', after: { type: 'String' } },
            { type: 'removed', field: 'code', before: { type: 'String' } },
          ],
          indexChanges: [
            { type: 'added', fields: { price: 1 } },
            { type: 'removed', fields: { name: 1 } },
          ],
        },
      },
    };
    const filePath = generateStub(result, 'idx-v5', 'idx-v6', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain('$set');
    expect(content).toContain('$unset');
    expect(content).toContain('createIndex');
    expect(content).toContain('dropIndex');
  });

  it('all index operations are commented out by default', () => {
    const result: DiffResult = {
      collections: {
        Log: {
          type: 'modified',
          indexChanges: [
            { type: 'added', fields: { ts: -1 } },
            { type: 'removed', fields: { old: 1 } },
          ],
        },
      },
    };
    const filePath = generateStub(result, 'idx-v7', 'idx-v8', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split('\n');
    const indexLines = lines.filter(l => l.includes('createIndex') || l.includes('dropIndex'));
    expect(indexLines.length).toBeGreaterThan(0);
    indexLines.forEach(line => {
      expect(line.trimStart()).toMatch(/^\/\//);
    });
  });

  it('includes compound index fields in the stub', () => {
    const result: DiffResult = {
      collections: {
        Rent: {
          type: 'modified',
          indexChanges: [{ type: 'added', fields: { tenant: 1, dueDate: -1 } }],
        },
      },
    };
    const filePath = generateStub(result, 'idx-v9', 'idx-v10', testProject);
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain('tenant');
    expect(content).toContain('dueDate');
  });
});
