import * as fs from 'fs';
import * as path from 'path';
import { DiffResult } from './types';

export function generateStub(
  result: DiffResult,
  from: string,
  to: string,
  project: string
): string {
  const migrationsDir = path.resolve(process.cwd(), 'migrations', project);

  if (!fs.existsSync(migrationsDir)) {
    fs.mkdirSync(migrationsDir, { recursive: true });
  }

  const fileName = `${from}-to-${to}.js`.replace(/\s+/g, '-');
  const filePath = path.join(migrationsDir, fileName);

  const lines: string[] = [];
  lines.push(`// Auto-generated by mongoose-drift`);
  lines.push(`// Project: ${project}`);
  lines.push(`// From: ${from}  →  To: ${to}`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push(`//`);
  lines.push(`// Review carefully before running.`);
  lines.push(`// Renames appear as remove + add — update manually if needed.`);
  lines.push('');
  lines.push(`module.exports = {`);
  lines.push(`  async up(db) {`);

  for (const [collection, change] of Object.entries(result.collections)) {
    if (change.type === 'added') {
      lines.push(`    // TODO: New collection '${collection}' — no migration needed unless seeding data`);
    } else if (change.type === 'removed') {
      lines.push(`    // TODO: Collection '${collection}' removed — drop if safe`);
      lines.push(`    // await db.collection('${collection}').drop();`);
    } else if (change.type === 'modified' && change.changes) {
      lines.push(`    // Collection: ${collection}`);

      for (const fieldChange of change.changes) {
        if (fieldChange.type === 'added') {
          lines.push(`    // TODO: Add field '${fieldChange.field}'`);
          lines.push(`    // await db.collection('${collection}').updateMany({}, { $set: { ${fieldChange.field}: null } });`);
        } else if (fieldChange.type === 'removed') {
          lines.push(`    // TODO: Remove field '${fieldChange.field}' — verify no data dependency first`);
          lines.push(`    // await db.collection('${collection}').updateMany({}, { $unset: { ${fieldChange.field}: '' } });`);
        } else if (fieldChange.type === 'modified') {
          lines.push(`    // TODO: Field '${fieldChange.field}' was modified — handle data transformation`);
        } else if (fieldChange.type === 'renamed') {
          lines.push(`    // TODO: Rename '${fieldChange.renamedFrom}' → '${fieldChange.field}'`);
          lines.push(`    // await db.collection('${collection}').updateMany({}, { $rename: { '${fieldChange.renamedFrom}': '${fieldChange.field}' } });`);
        }
      }

      lines.push('');
    }
  }

  lines.push(`  },`);
  lines.push('');
  lines.push(`  async down(db) {`);
  lines.push(`    // TODO: Reverse the above operations`);
  lines.push(`  },`);
  lines.push(`};`);

  const content = lines.join('\n');
  fs.writeFileSync(filePath, content);

  console.log(`✔ Migration stub created: migrations/${project}/${fileName}`);
  return filePath;
}
